name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: temurin
      - name: Run tests
        run: sbt test scripted headerCheck scapegoat
